-- MySQL Script generated by MySQL Workbench
-- Sun 04 Dec 2016 02:40:02 PM PST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Slices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Slices` (
  `idSlices` INT(11) NOT NULL AUTO_INCREMENT,
  `Location` VARCHAR(45) NULL DEFAULT NULL,
  `Tourist` TINYINT(1) NULL DEFAULT NULL,
  `primary_criteria` INT(11) NULL DEFAULT NULL,
  `secondary_criteria` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idSlices`),
  INDEX `fk_Slices_1_idx` (`primary_criteria` ASC),
  INDEX `fk_Slices_2_idx` (`secondary_criteria` ASC),
  CONSTRAINT `fk_Slices_1`
    FOREIGN KEY (`primary_criteria`)
    REFERENCES `mydb`.`Matching_criteria` (`idMatching_criteria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Slices_2`
    FOREIGN KEY (`secondary_criteria`)
    REFERENCES `mydb`.`Matching_criteria` (`idMatching_criteria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Matching_criteria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Matching_criteria` (
  `idMatching_criteria` INT(11) NOT NULL AUTO_INCREMENT,
  `Alchohol` INT(11) NULL DEFAULT NULL,
  `number_of_people` INT(11) NULL DEFAULT NULL,
  `indoors` INT(11) NULL DEFAULT NULL,
  `idSlices` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idMatching_criteria`),
  INDEX `fk_Matching_criteria_1_idx` (`idSlices` ASC),
  CONSTRAINT `fk_Matching_criteria_1`
    FOREIGN KEY (`idSlices`)
    REFERENCES `mydb`.`Slices` (`idSlices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `idUsers` INT(11) NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NULL DEFAULT NULL,
  `Password` BLOB NULL DEFAULT NULL,
  `Email` VARCHAR(45) NULL DEFAULT NULL,
  `Date` DATE NULL DEFAULT NULL,
  `favorite_criteria` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idUsers`),
  INDEX `fk_Users_1_idx` (`favorite_criteria` ASC),
  CONSTRAINT `fk_Users_1`
    FOREIGN KEY (`favorite_criteria`)
    REFERENCES `mydb`.`Matching_criteria` (`idMatching_criteria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reviews` (
  `idReviews` INT(11) NOT NULL AUTO_INCREMENT,
  `Rating` VARCHAR(45) NULL DEFAULT NULL,
  `Summary` VARCHAR(45) NULL DEFAULT NULL,
  `idSlices` INT(11) NULL DEFAULT NULL,
  `idUsers` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idReviews`),
  INDEX `fk_Reviews_1_idx` (`idSlices` ASC),
  INDEX `fk_Reviews_2_idx` (`idUsers` ASC),
  CONSTRAINT `fk_Reviews_1`
    FOREIGN KEY (`idSlices`)
    REFERENCES `mydb`.`Slices` (`idSlices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reviews_2`
    FOREIGN KEY (`idUsers`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
